version: '3.6'

#
# [ server stack ]
#
services:

  postgres:
    image: public.ecr.aws/docker/library/postgres:14-alpine
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${POSTGRES_SCHEMA}
      POSTGRES_USER: ${POSTGRES_ROOT_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - public
      - db_net
    volumes:
      #- ./tools/sql:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_DEV_PORT}:5432/tcp"

  redis:
    image: public.ecr.aws/docker/library/redis:7-alpine
    restart: unless-stopped
    networks:
      - public
    ports:
      - "${REDIS_DEV_PORT}:6379/tcp"

  search:
    image: opensearchproject/opensearch:2.11.0
    environment:
      cluster.name: fusionauth
      discovery.type: single-node
      node.name: search
      plugins.security.disabled: 'true'
      bootstrap.memory_lock: 'true'
      OPENSEARCH_JAVA_OPTS: ${OPENSEARCH_JAVA_OPTS}
    healthcheck:
      interval: 10s
      retries: 80
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:9200/
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    volumes:
      - search_data:/usr/share/opensearch/data
    networks:
      - search_net

  fusionauth:
    image: fusionauth/fusionauth-app:latest
    depends_on:
      postgres:
        condition: service_healthy
      search:
        condition: service_healthy
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/postgres
      DATABASE_ROOT_USERNAME: ${POSTGRES_ROOT_USERNAME}
      DATABASE_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      FUSIONAUTH_APP_MEMORY: ${FUSIONAUTH_APP_MEMORY}
      FUSIONAUTH_APP_RUNTIME_MODE: ${FUSIONAUTH_APP_RUNTIME_MODE}
      FUSIONAUTH_APP_URL: http://fusionauth:9011
      SEARCH_SERVERS: http://search:9200
      SEARCH_TYPE: elasticsearch
    healthcheck:
      test: curl --silent --fail http://localhost:9011/api/status -o /dev/null -w "%{http_code}"
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - db_net
      - search_net
    restart: unless-stopped
    ports:
      - 9011:9011
    volumes:
      - fusionauth_config:/usr/local/fusionauth/config

#
# [ volumes definition ]
#
volumes:
  postgres:
    name: "b-cube_postgres"
  fusionauth_config:
  search_data:

#
# [ networks definition ]
#
networks:
  public:
    external: true
    name: b-cube-public
  db_net:
    driver: bridge
  search_net:
    driver: bridge
